server:
  port: 8083
spring:
  cloud:
    gateway:
      routes:
        - id: empleado
          uri: lb://EMPLEADO
          predicates:
            - Path=/api/v1/empleado/**
          filters:
            - AutorizacionFilter
        - id: validar
          uri: lb://VALIDAREMPLEADO
          predicates:
            - Path=/api/v1/empleado-check/**
          filters:
            - AutorizacionFilter
        - id: autenticacion
            uri: lb://autenticacion
            predicates:
              - Path=/api/v1/autenticacion/**

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
#    enabled: false