apiVersion: apps/v1
kind: Deployment
metadata:
  name: validarempleado
  labels:
    app: validarempleado
spec:
  #replicas del pod
  replicas: 1
  template:
    metadata:
      name: validarempleado
      labels:
        app: validarempleado
    spec:
      containers:
        - name: validarempleado
          image: ffernacu/validarempleado:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: validarempleado
