server:
  port: 8082
spring:
  application:
    name: notificacion
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5431/notificacion
    username: nttdata
    password: 1234
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notificacion.queue
  routing-keys:
    internal-notification: internal.notification.routing-key
