server:
  port: 8083

spring:
  application:
    name: e-api-gateway
  cloud:
    gateway:
      routes:
        - id: empleado
          uri: lb://EMPLEADO
          predicates:
            - Path=/api/v1/empleado/**
        - id: validar
          uri: lb://VALIDAREMPLEADO
          predicates:
            - Path=/api/v1/empleado-check/**
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true