apiVersion: apps/v1
kind: Deployment
metadata:
  name: empleado
  labels:
    app: empleado
spec:
  replicas: 1
  template:
    metadata:
      name: empleado
      labels:
        app: empleado
    spec:
      containers:
        - name: empleado
          image: ffernacu/empleado:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: empleado